name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Set up environment
        run: cp .env.example .env
      - name: Generate key
        run: php artisan key:generate
      - name: Run tests
        run: php artisan test --parallel
